[Settings]
ID = "fc946949-bbfa-4d29-aa90-75a9103ca20d"

[build]
  publish = "public"
  command = "npm run build"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run preview"

[context.branch-deploy]
  command = "npm run preview"
